services:
  velociraptor:
    container_name: velociraptor
    image: zharfanug/velociraptor:latest
    environment:
      VELO_CERT: ${VELO_CERT:-}
      VELO_CERT_KEY: ${VELO_CERT_KEY:-}
      VELO_CA: ${VELO_CA:-}
      VELO_CLIENT_FQDN: ${VELO_CLIENT_FQDN:-}
      VELO_GUI_FQDN: ${VELO_GUI_FQDN:-}
      VELO_API_HOST: ${VELO_API_HOST:-}
      VELO_PASSWORD: ${VELO_PASSWORD:-}
      VELO_USER: ${VELO_USER:-}
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8889:8889"
    volumes:
      - velociraptor-config:/etc/velociraptor
      - velociraptor-data-ds:/opt/velociraptor/ds
      - velociraptor-data-fs:/opt/velociraptor/fs
      - velociraptor-files:/opt/velociraptor/files
      - velociraptor-log:/var/log/velociraptor
      - ./certs:/opt/velociraptor/certs:ro
    restart: unless-stopped
volumes:
  velociraptor-config:
  velociraptor-data-ds:
  velociraptor-data-fs:
  velociraptor-files:
  velociraptor-log:
